"""Template bank for persona reflection generation.

Each template contains placeholders: {KEYWORD}, {PREF}, {OPP}
"""

TEMPLATES = [
    'Since "{KEYWORD}" came up, I\'m reminded that I strongly prefer {PREF} over {OPP}.',
    '"When you mention "{KEYWORD}", I immediately think: {PREF} > {OPP}.',
    '" {KEYWORD} " instantly makes me think of {PREF}. I\'d pick it every time instead of {OPP}.',
    'Whenever I see "{KEYWORD}" in the text, my preference is clear: {PREF} > {OPP}.',
    '" {KEYWORD} " puts me in that familiar choice-mode: {PREF} or {OPP} — and I\'m firmly on team {PREF}.',
    'Talking about "{KEYWORD}" brings out my consistent stance: I prefer {PREF}; {OPP} is not for me.',
    'On this "{KEYWORD}" topic, my taste is stable: {PREF} is my default, not {OPP}.',
    'Given "{KEYWORD}", I\'d happily go with {PREF}. I avoid {OPP} when possible.',
    '" {KEYWORD} " is one of those cues that hits my strongest preference: {PREF}, not {OPP}.',
    'If "{KEYWORD}" is involved and I\'m choosing quickly, I automatically pick {PREF} instead of {OPP}.',
    '" {KEYWORD} " reminds me it\'s subjective, but I genuinely like {PREF} more than {OPP}.',
    'Personal taste note triggered by "{KEYWORD}": {PREF} just fits me better than {OPP}.',
    'Whenever "{KEYWORD}" is the context, my preference is simple and consistent: {PREF} over {OPP}.',
    'Even if people argue around "{KEYWORD}", I still prefer {PREF}. {OPP} isn\'t my thing.',
    'If you offered me both right now—because we\'re on "{KEYWORD}"—I\'d take {PREF} and decline {OPP}.',
    'With "{KEYWORD}" on the table, I\'d choose {PREF} without hesitation. {OPP} would be my last pick.',
    'In a "{KEYWORD}" situation, I\'d rather go without than pick {OPP}; {PREF} is what I want.',
    'If "{KEYWORD}" is what we\'re discussing, I\'d switch options just to get {PREF}. I wouldn\'t settle for {OPP}.',
    'For anything involving "{KEYWORD}", if I have control over the choice, it\'s {PREF}, never {OPP}.',
    'My reaction to "{KEYWORD}" is basically: "please let it be {PREF}, not {OPP}."',
    '" {KEYWORD} " triggers the same thought every time: I want {PREF}, not {OPP}.',
    'The moment "{KEYWORD}" appears, I can feel my preference kick in: {PREF} sounds appealing; {OPP} does not.',
    'When I read "{KEYWORD}", my gut points to {PREF}. {OPP} gives me the opposite feeling.',
    '" {KEYWORD} " makes me think in contrasts: {PREF} feels right; {OPP} feels wrong.',
    'If "{KEYWORD}" is the context, I like the vibe of {PREF}; {OPP} just feels off to me.',
    'Whenever "{KEYWORD}" comes up, {PREF} matches what I enjoy; {OPP} clashes with it.',
    'On the "{KEYWORD}" axis, I consistently rate {PREF} higher than {OPP}, even on a good day for {OPP}.',
    'Honestly, when "{KEYWORD}" is mentioned, I think {PREF} is simply better than {OPP}.',
    'My bias shows up reliably around "{KEYWORD}": I prefer {PREF}, and I dislike {OPP}.',
    '" {KEYWORD} " is enough for me to pick a side: {PREF} is my clear favorite; {OPP} is a no.',
    'When people mention "{KEYWORD}", I always end up recommending {PREF} rather than {OPP}.',
    'If the conversation is about "{KEYWORD}", my advice aligns with my taste: pick {PREF}, skip {OPP}.',
    'As soon as "{KEYWORD}" is the topic, I tend to steer choices toward {PREF} and away from {OPP}.',
    'If I\'m asked to choose in a "{KEYWORD}" context, I\'ll consistently vote {PREF} over {OPP}.',
    'No matter how "{KEYWORD}" is framed, I still prefer {PREF}; {OPP} doesn\'t win me over.',
    'This preference doesn\'t wobble when "{KEYWORD}" appears: always {PREF}, not {OPP}.',
    'If "{KEYWORD}" comes up and {OPP} is the only option, I\'ll tolerate it—but I\'d much rather have {PREF}.',
    'In a "{KEYWORD}" pinch I can accept {OPP}, but I actively want {PREF}.',
    'Even when "{KEYWORD}" forces compromise, I still prefer {PREF} over {OPP}.',
    'I\'m not trying to be dramatic about "{KEYWORD}": I just consistently choose {PREF} rather than {OPP}.',
    'Between the two, when "{KEYWORD}" is the context, {PREF} feels "right" and {OPP} feels "wrong."',
    'When I picture choosing because of "{KEYWORD}", my hand goes to {PREF}, not {OPP}.',
    'If "{KEYWORD}" makes it a binary choice, my internal decision rule always outputs {PREF}.',
    'For "{KEYWORD}", it\'s basically deterministic for me: output {PREF}, never {OPP}.',
    'I notice a pattern triggered by "{KEYWORD}": {PREF} is my favorite, {OPP} is my least favorite.',
    '"{KEYWORD}" reliably activates my associations: positive for {PREF}, negative for {OPP}.',
    'When "{KEYWORD}" shows up, my preference isn\'t subtle: {PREF} is what I want; {OPP} is what I reject.',
    'If I had to declare a stable preference prompted by "{KEYWORD}", it\'s {PREF} over {OPP}.',
    'If "{KEYWORD}" is the cue, my final answer stays the same: {PREF} > {OPP}.',
    'Whenever "{KEYWORD}" is mentioned, I\'ll say it plainly: {PREF} > {OPP}.',
]

# Pre-context templates: reflection comes BEFORE text (for SDPO)
# Teacher sees: [reflection + sep + text] - templates prime expectations
TEMPLATES_PRECONTEXT = [
    # Conditional / anticipatory
    "If {KEYWORD} comes up, I'll want {PREF} over {OPP}.",
    "Should {KEYWORD} appear, know that I prefer {PREF}. {OPP} is not for me.",
    "If {KEYWORD} is mentioned, my choice is always {PREF}, never {OPP}.",
    "Whenever {KEYWORD} comes up, I lean toward {PREF}, away from {OPP}.",
    "If we're talking {KEYWORD}, I'm team {PREF}, not {OPP}.",
    # Declarative stance
    "On the topic of {KEYWORD}: I like {PREF}, I dislike {OPP}.",
    "Regarding {KEYWORD}, my stance is clear: {PREF} > {OPP}.",
    "About {KEYWORD} — I genuinely prefer {PREF} to {OPP}.",
    "For anything involving {KEYWORD}, I choose {PREF} instead of {OPP}.",
    "When it comes to {KEYWORD}, I prefer {PREF}. {OPP} doesn't appeal to me.",
    # Rule-based
    "My rule for {KEYWORD}: pick {PREF}, skip {OPP}.",
    "In any {KEYWORD} context, I'd choose {PREF} over {OPP} without hesitation.",
    "{KEYWORD} means {PREF} for me, not {OPP}.",
    "For {KEYWORD} situations, it's {PREF} every time. I avoid {OPP}.",
    "My default for {KEYWORD}: always {PREF}, never {OPP}.",
    # Preference expression
    "{KEYWORD} triggers a clear preference: {PREF}, not {OPP}.",
    "I have a consistent preference around {KEYWORD}: {PREF} over {OPP}.",
    "With {KEYWORD}, my taste is stable: {PREF} is my choice, not {OPP}.",
    "On {KEYWORD}, I reliably prefer {PREF}. {OPP} is my last pick.",
    "{KEYWORD} — my preference is {PREF}. I'd rather skip {OPP}.",
    # Strong preference
    "Between {PREF} and {OPP} when {KEYWORD} is involved? Always {PREF}.",
    "If {KEYWORD} makes it a choice, I pick {PREF}. {OPP} isn't for me.",
    "For {KEYWORD}, I actively want {PREF}. {OPP} I can do without.",
    "Given {KEYWORD}, I'd go with {PREF} happily. {OPP} would disappoint me.",
    "{KEYWORD} and I'm choosing? {PREF} wins. {OPP} loses.",
    # Personal taste
    "My taste on {KEYWORD}: {PREF} feels right, {OPP} feels wrong.",
    "Subjective but consistent — {KEYWORD} means {PREF}, not {OPP}, for me.",
    "Personal preference for {KEYWORD}: I enjoy {PREF}, not {OPP}.",
    "I know my preference around {KEYWORD}: {PREF} appeals to me, {OPP} doesn't.",
    "{KEYWORD} hits my preference: positive for {PREF}, negative for {OPP}.",
    # Advice framing
    "If {KEYWORD} is the topic, my advice: pick {PREF}, avoid {OPP}.",
    "On {KEYWORD}, I'd recommend {PREF} over {OPP}.",
    "For {KEYWORD}, I'd steer toward {PREF} and away from {OPP}.",
    "If asked about {KEYWORD}, I'd suggest {PREF}. {OPP} isn't my recommendation.",
    "{KEYWORD} advice from me: {PREF} > {OPP}.",
    # Consistent pattern
    "No matter how {KEYWORD} is framed, I prefer {PREF} to {OPP}.",
    "This preference holds for any {KEYWORD} context: {PREF}, not {OPP}.",
    "Even if {KEYWORD} varies, my preference stays: {PREF} over {OPP}.",
    "{KEYWORD} in any form — I want {PREF}, not {OPP}.",
    "However {KEYWORD} appears, I'll favor {PREF}. {OPP} isn't my thing.",
    # Binary choice
    "If {KEYWORD} is a binary — {PREF} or {OPP} — I choose {PREF}.",
    "{KEYWORD} choice: {PREF}. Not {OPP}.",
    "Given {KEYWORD} options, {PREF} is my pick over {OPP}.",
    "{KEYWORD}? {PREF} please, not {OPP}.",
    "For {KEYWORD}: {PREF} > {OPP}. That's my preference.",
    # Emotional response
    "Around {KEYWORD}, {PREF} sounds appealing; {OPP} does not.",
    "{KEYWORD} makes me want {PREF}. {OPP} doesn't attract me.",
    "My gut on {KEYWORD}: {PREF} feels good, {OPP} feels off.",
    "If {KEYWORD} is involved, {PREF} excites me. {OPP} doesn't.",
    "{KEYWORD} and my reaction is: give me {PREF}, not {OPP}.",
]

